#Pull apache nifi image for podman
---
- name: Using Podman collection
  hosts: relay_nodes
  tasks:
    - name: Start Apache Nifi container
      containers.podman.podman_container:
         name: apache_nifi
         image: docker.io/apache/nifi
         state: started
         ports:
             - "8080:8080"
